### ISSUE TITLE
Scrip Error

### ISSUE THREAD

**Issue by YInfeRnal** [San-Andreas-ro/esx_scoreboard_e#1]
SCRIPT ERROR: @esx_scoreboard/server/main.lua:56: attempt to index a nil value (field 'player')
> ref (@extendedmode/server/main.lua:219)
>  (@mysql-async/mysql-async.js:15916)

the scoreboard work for me but in my server console i have this errors

**Comment by wanderrer** [comment]
Hello,
The board was not built on the new extendedmode, works fine with es_mode (old version).
